/* Quest scenery and personal collections. No additional network requests. */
(()=>{
"use strict";
const destinations=[
 {id:"meadow",name:"Meadow Bridge",mission:"Bring the meadow back to life",sky:"#d9f4ed",ground:"#9ad4a3",accent:"#317b62"},
 {id:"cove",name:"Crystal Cove",mission:"Light a path through the cove",sky:"#eee6ff",ground:"#b8a7df",accent:"#7051b0"},
 {id:"harbour",name:"Star Harbour",mission:"Prepare the harbour for launch",sky:"#dceeff",ground:"#94bfdc",accent:"#326d9a"}
];
const treasures=[{id:"tree",name:"Cloud tree"},{id:"crystal",name:"Glow crystal"},{id:"rocket",name:"Pocket rocket"},{id:"flower",name:"Sunflower"},{id:"tent",name:"Explorer’s tent"},{id:"planet",name:"Little planet"},{id:"mushroom",name:"Marshmallow mushroom"},{id:"flag",name:"Quest flag"},{id:"star",name:"Golden star"}];
function state(l){const value=l.adventure||{};l.adventure=Object.assign(value,{destination:destinations.some(d=>d.id===value.destination)?value.destination:"meadow",unlocked:[...new Set(Array.isArray(value.unlocked)?value.unlocked:[])].filter(id=>treasures.some(t=>t.id===id)),placed:[...new Set(Array.isArray(value.placed)?value.placed:[])].filter(id=>treasures.some(t=>t.id===id)),rounds:Math.max(0,Math.floor(Number(value.rounds)||0))});l.adventure.placed=l.adventure.placed.filter(id=>l.adventure.unlocked.includes(id)).slice(0,5);return l.adventure}
function award(l,s){if(!s||s.index<1||Number.isFinite(s.total)&&s.index<s.total)return null;const a=state(l),next=treasures.find(t=>!a.unlocked.includes(t.id));a.rounds++;if(next){a.unlocked.push(next.id);if(a.placed.length<5)a.placed.push(next.id)}return next||null}
function decoration(id,x,y){const objects={tree:'<rect x="-5" y="-27" width="10" height="28" rx="4" fill="#9b6945"/><circle cx="0" cy="-42" r="22" fill="#66b986"/><circle cx="-13" cy="-35" r="16" fill="#8fd3a4"/>',crystal:'<path d="m-16 0 1-30 15-18 15 18 1 30Z" fill="#a381ec"/><path d="M0-48 0 0 15-30Z" fill="#cfb8ff"/>',rocket:'<path d="M-12 0v-29q12-25 24 0V0Z" fill="#fff9e9"/><circle cy="-24" r="7" fill="#71bde2"/><path d="m-12-12-9 15 9-3M12-12l9 15-9-3" fill="#ee819c"/>',flower:'<path d="M0 0v-34" stroke="#468e63" stroke-width="5"/><path d="M0-12q-20-18-16 0Z" fill="#78bc84"/><circle cy="-39" r="16" fill="#ffda64"/><circle cy="-39" r="8" fill="#b97b48"/>',tent:'<path d="m-28 0 28-42 28 42Z" fill="#ffb46c"/><path d="M0-42 0 0h28Z" fill="#e78d5f"/><path d="m-12 0 12-23 12 23Z" fill="#655277"/>',planet:'<circle cy="-23" r="19" fill="#e6b2e9"/><ellipse cy="-23" rx="31" ry="8" fill="none" stroke="#f9d789" stroke-width="5" transform="rotate(-20 0 -23)"/>',mushroom:'<rect x="-8" y="-23" width="16" height="24" rx="7" fill="#fff4e0"/><path d="M-25-20a25 25 0 0 1 50 0Z" fill="#f48caa"/><circle cx="-9" cy="-28" r="4" fill="#fff1e5"/><circle cx="10" cy="-32" r="5" fill="#fff1e5"/>',flag:'<path d="M-10 0v-47" stroke="#f8eee0" stroke-width="5"/><path d="M-8-46h33l-10 12 10 12H-8Z" fill="#ef8dab"/>',star:'<path d="m0-46 7 14 16 2-12 12 3 16L0-10-14-2l3-16-12-12 16-2Z" fill="#ffcf52"/>'};return `<g transform="translate(${x} ${y})" filter="url(#clay)">${objects[id]||""}</g>`}
function scene(l,progress=0,journey=false){const a=state(l),d=destinations.find(d=>d.id===a.destination),p=Math.max(0,Math.min(1,progress));return `<svg class="quest-landscape" viewBox="0 0 640 190" role="img" aria-label="${d.name}: ${a.placed.length} decorations${journey?`, ${Math.round(p*100)} percent of the journey complete`:""}"><defs><filter id="clay" x="-50%" y="-50%" width="200%" height="200%"><feDropShadow dx="0" dy="4" stdDeviation="2" flood-color="#493455" flood-opacity=".18"/></filter></defs><rect width="640" height="190" rx="24" fill="${d.sky}"/><circle cx="550" cy="39" r="22" fill="#fff3a8"/><path d="M0 122Q100 62 210 119T440 109T640 110V190H0Z" fill="${d.ground}"/><path d="M0 157Q110 112 250 151T640 142V190H0Z" fill="${d.accent}" opacity=".16"/><path d="M45 155Q180 115 290 150T595 139" stroke="#fff6df" stroke-width="17" fill="none" stroke-linecap="round"/>${a.placed.map((id,i)=>decoration(id,100+i*105,113+(i%2)*6)).join("")}${journey?`<g class="journey-traveller" style="transform:translate(${45+p*540}px,143px)"><circle r="13" fill="#7655e8" stroke="#fff" stroke-width="4"/><path d="m-5 0 4 4 7-9" fill="none" stroke="#fff" stroke-width="3" stroke-linecap="round"/></g>`:""}<g transform="translate(590 98)" filter="url(#clay)"><rect x="-18" width="36" height="30" rx="7" fill="#ecad59"/><rect x="-20" y="-6" width="40" height="15" rx="6" fill="#ffd373"/><rect x="-3" y="4" width="6" height="12" rx="2" fill="#fff0a8"/></g></svg>`}
function element(id,tag="section"){let e=document.getElementById(id);if(!e){e=document.createElement(tag);e.id=id}return e}
function home(l,save){const root=element("questWorld","button");document.getElementById("gamesGrid").prepend(root);root.className="game-tile world-tile";root.innerHTML=`<div class="game-preview mini-home-preview">${miniPreview("line")}</div><span class="game-tile-copy"><strong>Mini-games</strong><span>Jump along number trails and share treasure.</span></span>`;root.setAttribute("aria-label","Open Mini-games");root.onclick=()=>miniGames(l,save);const button=element("myCollection","button");button.className="secondary collection-launch";button.textContent="My collection";button.onclick=()=>collection(l,save);document.getElementById("playGamesTitle").after(button);}
function journey(l,s){document.getElementById("questJourney")?.remove();document.getElementById("gameScreen").classList.remove("quest-finale")}
function results(l,reward,s,save){document.getElementById("gameScreen").classList.remove("quest-finale");const root=element("questReward","div");document.querySelector("#resultsScreen .overview").before(root);root.className="quest-reward";const full=s.index>0&&(!Number.isFinite(s.total)||s.index>=s.total);root.innerHTML=`${scene(l)}<h2>${reward?`${reward.name} unlocked!`:full?"Your world is growing":"Keep exploring"}</h2><p>${reward?"Your new decoration is ready for your collection.":full?"Another adventure completed. Choose how your world looks.":"Finish a full round to earn a decoration."}</p>`;const b=document.createElement("button");b.className="secondary";b.textContent="My collection";b.onclick=()=>collection(l,save);root.appendChild(b)}
function collection(l,save){const a=state(l),dialog=element("worldDialog","dialog");if(!dialog.isConnected)document.body.appendChild(dialog);dialog.innerHTML='<div class="dialog-body"><div class="dialog-top"><div><p class="eyebrow">Your collection</p><h2>My collection</h2></div><button class="close" aria-label="Close collection">×</button></div><p>Choose up to five decorations for your world. Complete a full quest to earn the next one.</p><div class="collection-grid"></div><p class="small" role="status" id="collectionStatus"></p></div>';dialog.querySelector(".close").onclick=()=>dialog.close();const preview=document.createElement("div");preview.className="collection-preview";preview.innerHTML=scene(l);dialog.querySelector(".collection-grid").before(preview);const grid=dialog.querySelector(".collection-grid");treasures.forEach(t=>{const unlocked=a.unlocked.includes(t.id),b=document.createElement("button");b.className="collectible";b.disabled=!unlocked;b.setAttribute("aria-pressed",String(a.placed.includes(t.id)));b.innerHTML=`<svg viewBox="0 0 90 70" aria-hidden="true">${decoration(t.id,45,60)}</svg><strong>${t.name}</strong><span>${unlocked?a.placed.includes(t.id)?"In your world":"Add to world":"Complete more quests"}</span>`;b.onclick=()=>{if(a.placed.includes(t.id))a.placed=a.placed.filter(id=>id!==t.id);else if(a.placed.length<5)a.placed.push(t.id);else{dialog.querySelector("#collectionStatus").textContent="Remove one decoration to make space for this one.";return}save();homeWithGames(l,save);dialog.close();collection(l,save)};grid.appendChild(b)});dialog.showModal()}
let miniActive=false;
function miniPreview(kind){return kind==="line"?'<svg viewBox="0 0 300 140" aria-hidden="true"><rect width="300" height="140" rx="18" fill="#e6ddfa"/><path d="M30 96h240" stroke="#aa91d4" stroke-width="6" stroke-linecap="round"/><path d="M60 96Q90 18 120 96Q150 18 180 96" fill="none" stroke="#7655e8" stroke-width="5" stroke-dasharray="6 5"/><g fill="#5336c1" font-size="20" text-anchor="middle" font-family="system-ui"><text x="60" y="125">2</text><text x="120" y="125">4</text><text x="180" y="125">6</text></g><circle cx="180" cy="85" r="14" fill="#ffd84b" stroke="#fff" stroke-width="4"/></svg>':'<svg viewBox="0 0 300 140" aria-hidden="true"><rect width="300" height="140" rx="18" fill="#fff2c5"/><rect x="28" y="30" width="105" height="90" rx="20" fill="#e6ddfa" stroke="#fff" stroke-width="4"/><rect x="167" y="30" width="105" height="90" rx="20" fill="#e6ddfa" stroke="#fff" stroke-width="4"/><g fill="#7655e8"><circle cx="60" cy="60" r="11"/><circle cx="101" cy="60" r="11"/><circle cx="60" cy="93" r="11"/><circle cx="101" cy="93" r="11"/><circle cx="199" cy="60" r="11"/><circle cx="240" cy="60" r="11"/><circle cx="199" cy="93" r="11"/><circle cx="240" cy="93" r="11"/></g></svg>'}
function miniGames(l,save){const dialog=element("miniDialog","dialog");if(!dialog.isConnected)document.body.appendChild(dialog);dialog.className="mini-dialog";dialog.innerHTML=`<div class="dialog-body"><div class="dialog-top"><div><p class="eyebrow">Play and discover</p><h2>Mini-games</h2></div><button class="close" aria-label="Close mini-games">×</button></div><p>Choose a game. The puzzles match your learner’s class.</p><div class="mini-choices"><button class="collectible" data-game="line">${miniPreview("line")}<strong>Number Trail</strong><span>Jump along a number line to add and subtract.</span><b class="mini-play">Play Number Trail →</b></button><button class="collectible" data-game="share">${miniPreview("share")}<strong>Share the Treasure</strong><span>Share counters equally to discover division.</span><b class="mini-play">Play Share the Treasure →</b></button></div><p class="small">Three puzzles · no timer · finish to earn a decoration</p></div>`;dialog.querySelector(".close").onclick=()=>dialog.close();dialog.querySelectorAll("[data-game]").forEach(b=>b.onclick=()=>startMini(b.dataset.game,l,save,dialog));dialog.showModal()}
function startMini(kind,l,save,dialog){
 miniActive=true;let index=0,firstTry=0,helped=0,independent=0,timer,ghost;
 function cleanup(){clearTimeout(timer);ghost?.remove();ghost=null;}
 dialog.onclose=()=>{cleanup();miniActive=false;};
 function puzzle(){
  cleanup();const upper=l.classLevel>=5,mid=l.classLevel>=3,subtract=index%2===1,step=upper?10:mid?5:1,start=(upper?40:mid?15:4)+index*step,difference=(index+3)*step,target=subtract?start-difference:start+difference,groups=upper?4:mid?3:2,each=upper?5+index:mid?3+index:2+index,total=groups*each;
  const low=Math.max(0,Math.min(start,target)-2*step),high=Math.max(start,target)+2*step;
  let position=start,checks=0,tipUsed=false,counts=Array(groups).fill(0),remaining=total,solved=false;
  dialog.innerHTML=`<div class="dialog-body"><div class="dialog-top"><div><p class="eyebrow">Puzzle ${index+1} of 3</p><h2>${kind==="line"?"Number Trail":"Share the Treasure"}</h2></div><button class="close" aria-label="Close mini-game">×</button></div><p class="mini-question">${kind==="line"?`${start} ${subtract?"−":"+"} ${difference} = ?`:`Share ${total} gold coins equally between ${groups} treasure buckets.`}</p><p>${kind==="line"?"Tap the number line to choose a landing point, or use the jump buttons.":"Drag a gold coin into a bucket, or tap a bucket to give it a coin. Tap a shared coin to return it."}</p><aside class="mini-tip" id="miniTipPanel" hidden></aside><div id="miniBoard"></div><div class="mini-controls"></div><p id="miniFeedback" role="status" aria-live="polite"></p><div class="actions"><button class="secondary" id="miniTip">Show a tip</button><button class="primary" id="miniCheck">Check my answer</button></div></div>`;
  dialog.querySelector(".close").onclick=()=>dialog.close();
  const board=dialog.querySelector("#miniBoard"),controls=dialog.querySelector(".mini-controls"),feedback=dialog.querySelector("#miniFeedback"),check=dialog.querySelector("#miniCheck"),tipPanel=dialog.querySelector("#miniTipPanel");
  function moved(){feedback.textContent="";feedback.className="";draw();}
  function transfer(from,to){if(solved||from===to||from>=0&&!counts[from]||from<0&&!remaining)return;if(from<0)remaining--;else counts[from]--;if(to<0)remaining++;else counts[to]++;moved();}
  function coin(from,preview=false){
   const dot=document.createElement("button");dot.className="share-counter gold-coin"+(from>=0&&preview?" shared-preview":"");dot.textContent=from>=0&&preview?String(from+1):"★";
   dot.setAttribute("aria-label",from<0?"Gold coin: drag into a treasure bucket":`Return a coin from bucket ${from+1}`);dot.disabled=solved;
   let drag=null,suppressClick=false;
   dot.onclick=()=>{if(suppressClick){suppressClick=false;return;}if(from>=0)transfer(from,-1);else{feedback.textContent="Drag this coin to a bucket, or tap the bucket’s Add coin button.";feedback.className="mini-reminder";}};
   dot.onpointerdown=e=>{if(solved||e.button!==0)return;drag={x:e.clientX,y:e.clientY};dot.setPointerCapture(e.pointerId);};
   dot.onpointermove=e=>{if(!drag)return;if(!ghost&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6){ghost=dot.cloneNode(true);ghost.className="gold-coin coin-drag-ghost";ghost.removeAttribute("id");ghost.setAttribute("aria-hidden","true");dialog.appendChild(ghost);}
    if(ghost){e.preventDefault();ghost.style.left=e.clientX+"px";ghost.style.top=e.clientY+"px";dialog.querySelectorAll(".sharing-group").forEach(b=>{const r=b.getBoundingClientRect();b.classList.toggle("coin-drop-target",e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom);});}
   };
   function end(e,cancel=false){if(!drag)return;drag=null;const dragged=!!ghost;ghost?.remove();ghost=null;dialog.querySelectorAll(".coin-drop-target").forEach(b=>b.classList.remove("coin-drop-target"));if(dragged){suppressClick=true;if(!cancel){const hit=document.elementFromPoint(e.clientX,e.clientY),bucket=hit?.closest(".sharing-group");if(bucket)transfer(from,Number(bucket.dataset.group));else if(hit?.closest(".counter-pool"))transfer(from,-1);}}}
   dot.onpointerup=e=>end(e);dot.onpointercancel=e=>end(e,true);dot.onlostpointercapture=e=>end(e,true);return dot;
  }
  function draw(){
   if(kind==="line"){
    board.innerHTML=`<div class="number-trail"><svg viewBox="0 0 560 100" aria-hidden="true"><path d="M25 48h510" stroke="#bfb0d4" stroke-width="6" stroke-linecap="round"/>${Array.from({length:(high-low)/step+1},(_,i)=>{const n=low+i*step,x=25+(n-low)/(high-low)*510;return `<path d="M${x} 40v16" stroke="#8b78a4" stroke-width="2"/><text x="${x}" y="80" text-anchor="middle" fill="#554568" font-size="16">${n}</text>`}).join("")}<circle cx="${25+(position-low)/(high-low)*510}" cy="34" r="13" fill="${solved?"#3bb789":"#7655e8"}" stroke="#fff" stroke-width="4"/></svg><input class="trail-range" type="range" min="${low}" max="${high}" step="${step}" value="${position}" aria-label="Choose a number on the trail" ${solved?"disabled":""}><strong>Landing on ${position}</strong></div>`;
    function landing(value){if(solved)return;position=Math.max(low,Math.min(high,low+Math.round((value-low)/step)*step));feedback.textContent="";feedback.className="";board.querySelector("circle").setAttribute("cx",String(25+(position-low)/(high-low)*510));board.querySelector("strong").textContent=`Landing on ${position}`;board.querySelector(".trail-range").value=String(position);}
    board.querySelector(".trail-range").oninput=e=>landing(Number(e.target.value));
    const line=board.querySelector("svg");
    function point(e){const r=line.getBoundingClientRect();landing(low+((e.clientX-r.left)/r.width*560-25)/510*(high-low));}
    line.onpointerdown=e=>{if(solved||e.button!==0)return;e.preventDefault();line.setPointerCapture(e.pointerId);point(e);};
    line.onpointermove=e=>{if(e.buttons===1)point(e);};
    controls.replaceChildren();[-step,step].forEach(jump=>{const b=document.createElement("button");b.className="secondary";b.textContent=`Jump ${jump>0?"+":"−"}${Math.abs(jump)}`;b.disabled=solved||position+jump<low||position+jump>high;b.onclick=()=>{position+=jump;moved();};controls.appendChild(b);});
    const reset=document.createElement("button");reset.className="linkbtn";reset.textContent="Back to start";reset.disabled=solved;reset.onclick=()=>{position=start;moved();};controls.appendChild(reset);
   }else{
    board.replaceChildren();const pool=document.createElement("div");pool.className="counter-pool";const label=document.createElement("strong");label.textContent=`${remaining} ${remaining===1?"coin":"coins"} left to share`;pool.appendChild(label);
    const tray=document.createElement("div");tray.className="share-dots counter-tray";for(let n=0;n<remaining;n++)tray.appendChild(coin(-1));
    counts.forEach((count,i)=>{for(let n=0;n<count;n++)tray.appendChild(coin(i,true));});pool.appendChild(tray);
    const help=document.createElement("small");help.textContent="Numbered coins are in buckets. Tap one to bring it back.";pool.appendChild(help);board.appendChild(pool);
    const row=document.createElement("div");row.className="sharing-groups";row.style.setProperty("--buckets",String(Math.min(groups,3)));
    counts.forEach((count,i)=>{const box=document.createElement("div");box.className="sharing-group treasure-bucket";box.dataset.group=String(i);box.style.setProperty("--bucket",["#9ccfc4","#cab3e5","#efaac1","#add3ec"][i%4]);
     const heading=document.createElement("strong");heading.className="bucket-title";heading.textContent=`Treasure ${i+1} · ${count} ${count===1?"coin":"coins"}`;box.appendChild(heading);
     const dots=document.createElement("div");dots.className="share-dots";for(let n=0;n<count;n++)dots.appendChild(coin(i));box.appendChild(dots);
     const give=document.createElement("button");give.className="secondary";give.textContent="+ Add coin";give.setAttribute("aria-label",`Give a coin to bucket ${i+1}, currently ${count}`);give.disabled=solved||remaining===0;give.onclick=()=>transfer(-1,i);box.appendChild(give);row.appendChild(box);
    });board.appendChild(row);
   }
  }
  draw();
  dialog.querySelector("#miniTip").onclick=()=>{
   if(!tipUsed){helped++;tipUsed=true;}tipPanel.hidden=!tipPanel.hidden;
   dialog.querySelector("#miniTip").textContent=tipPanel.hidden?"Show a tip":"Hide tip";
   tipPanel.innerHTML=kind==="line"?`<strong>${subtract?"Move left to subtract":"Move right to add"}</strong><p>Start at ${start}. Make ${difference/step} jumps of ${step} ${subtract?"left":"right"}.</p><div class="mini-tip-jumps" aria-label="${difference/step} jumps of ${step}">${Array.from({length:difference/step},()=>`<span>${subtract?"← −":"+"}${step}${subtract?"":" →"}</span>`).join("")}</div>`:`<strong>One coin each, then another round</strong><p>Give every bucket one coin before starting the next round. Keep going until the tray is empty. All buckets should have the same amount.</p>`;
  };
  check.onclick=()=>{
   if(solved)return;checks++;const correct=kind==="line"?position===target:remaining===0&&counts.every(n=>n===each);
   if(!correct){feedback.className="mini-error";feedback.textContent=kind==="line"?`Not yet. You landed on ${position}. Check the direction and number of jumps.`:remaining?`There are ${remaining} coins still to share.`:"Not equal yet. Drag a coin from a fuller bucket to a smaller one.";return;}
   solved=true;if(checks===1){firstTry++;if(!tipUsed)independent++;}draw();feedback.className="mini-success";
   feedback.textContent=kind==="line"?`✓ Correct! ${start} ${subtract?"−":"+"} ${difference} = ${target}.`:`✓ Perfect sharing! ${total} ÷ ${groups} = ${each}. Every bucket has ${each} coins.`;
   check.disabled=true;check.textContent=index===2?"Finishing…":"Next puzzle…";dialog.querySelector("#miniTip").disabled=true;
   let elapsed=0,last=performance.now();function advance(){if(!dialog.open)return;const now=performance.now();if(!document.hidden)elapsed+=Math.min(now-last,100);last=now;if(elapsed>=1200){index++;index<3?puzzle():complete();}else timer=setTimeout(advance,80);}timer=setTimeout(advance,80);
  };
 }
 function complete(){
  cleanup();const reward=award(l,{index:3,total:3});l.sessions++;l.totalAttempts+=3;l.totalCorrect+=firstTry;l.helped+=helped;
  l.completedResults.push({id:crypto.randomUUID(),completedAt:new Date().toISOString(),mode:kind==="line"?"Number Trail":"Share the Treasure",questions:3,correct:firstTry,score:3,independent});
  miniActive=false;save();homeWithGames(l,save);
  dialog.innerHTML=`<div class="dialog-body"><div class="dialog-top"><h2>Adventure complete!</h2><button class="close" aria-label="Close mini-game">×</button></div>${scene(l)}<p>${reward?`${reward.name} unlocked for your collection.`:"Your collection is complete. Make your world your own!"}</p><button class="primary" id="miniDone">Back to games</button></div>`;
  dialog.querySelector(".close").onclick=()=>dialog.close();dialog.querySelector("#miniDone").onclick=()=>dialog.close();
 }
 puzzle();
}
const renderHome=home;
function homeWithGames(l,save){renderHome(l,save);racerTile(l,save);const root=document.getElementById("gamesGrid");document.getElementById("cloudCrossingTile")?.remove();const island=document.createElement("button");island.id="cloudCrossingTile";island.className="game-tile cloud-tile";island.innerHTML='<img src="assets/cloud-crossing-preview.jpg" alt="" class="game-preview"><span class="game-tile-copy"><strong>Cloud Crossing</strong><span>Build a bridge, then pick a bouquet in a floating 3D world.</span></span>';island.onclick=async()=>{if(miniActive)return;miniActive=true;island.disabled=true;island.querySelector("strong").textContent="Opening the island…";try{const game=await import('./island.js?v=52');game.openIsland(l,{close:()=>{miniActive=false;homeWithGames(l,save)},sound:kind=>window.dispatchEvent(new CustomEvent('island-sound',{detail:kind})),celebrations:window.mathsQuest?.snapshot().settings.celebrations,complete:({firstTry,independent,hints,questions=3})=>{const reward=award(l,{index:questions,total:questions});l.sessions++;l.totalAttempts+=questions;l.totalCorrect+=firstTry;l.helped+=hints;l.completedResults.push({id:crypto.randomUUID(),completedAt:new Date().toISOString(),mode:'Cloud Crossing',questions,correct:firstTry,score:questions,independent});save();return reward;}});}catch(error){miniActive=false;document.querySelector('.island-dialog')?.close();island.disabled=false;island.querySelector("strong").textContent="Try opening Cloud Crossing again";console.error('Cloud Crossing could not open',error);}};document.getElementById("beatButton").before(island)}
function racerTile(l,save){
 document.getElementById("racerTile")?.remove();const b=document.createElement("button");b.id="racerTile";b.className="game-tile racer-tile";
 b.innerHTML='<img src="assets/turbo-trail-preview.png" alt="" class="game-preview"><span class="game-tile-copy"><strong>Turbo Trail</strong><span>Drive through the right numbers. Beat your personal best.</span></span>';
 b.onclick=async()=>{if(miniActive)return;miniActive=true;b.disabled=true;try{const game=await import('./racer.js?v=52');game.openRacer(l,{sound:window.mathsQuest?.snapshot().settings.sound,close:()=>{miniActive=false;homeWithGames(l,save)},complete:({questions,correct,independent,helped,best})=>{l.turboBest=Math.max(Number(l.turboBest)||0,best||correct);const reward=correct>=3?award(l,{index:correct,total:3}):null;l.sessions++;l.totalAttempts+=questions;l.totalCorrect+=correct;l.helped+=helped;l.completedResults.push({id:crypto.randomUUID(),completedAt:new Date().toISOString(),mode:'Turbo Trail',questions,correct,score:correct,independent});save();return reward;}});}catch(e){miniActive=false;document.querySelector('.racer-dialog')?.close();b.disabled=false;b.querySelector('strong').textContent='Try opening Turbo Trail again';console.error('Turbo Trail could not open',e);}};
 document.getElementById("beatButton").before(b);
}
window.questAdventure={home:homeWithGames,journey,results,award,state,inMini:()=>miniActive,endMini:()=>{document.getElementById("miniDialog")?.close();document.querySelector('.island-dialog')?.close();document.querySelector('.racer-dialog')?.close()}};
})();
