(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],rand=a=>a[Math.floor(Math.random()*a.length)],rint=(a,b)=>a+Math.floor(Math.random()*(b-a+1)),shuffle=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
const STORE="mathsQuestEveryoneV1",STRANDS={number:["🔢","Number"],algebra:["◆","Algebra"],measures:["📏","Measures"],shape:["◇","Shape & Space"],data:["▥","Data & Chance"]};
const TOPICS={
 place100:["Place value to 100","number","Tens, ones and number value"],add20:["Addition to 20","number","Counting on and number bonds"],sub20:["Subtraction to 20","number","Counting back and finding differences"],groups:["Equal groups","number","Early multiplication and sharing"],fractionsBasic:["Halves and wholes","number","Equal parts of shapes and sets"],patterns:["Patterns and rules","algebra","Continue and describe patterns"],measureEarly:["Money, time and measure","measures","Everyday measures and half hours"],shapeEarly:["Shape and position","shape","2-D shapes and spatial language"],dataEarly:["Simple data","data","Read picture charts and lists"],
 place1000:["Place value to 1,000","number","Hundreds, tens and ones"],add100:["Addition to 100","number","Mental and written strategies"],sub100:["Subtraction to 100","number","Difference and regrouping ideas"],tables2510:["×2, ×5 and ×10","number","Core multiplication patterns"],divisionBasic:["Sharing and division","number","Equal shares and inverse facts"],fractionsQuarter:["Halves and quarters","number","Fractions of shapes and amounts"],measure2:["Money, time and length","measures","Euro, quarter hours and units"],shape2:["2-D and 3-D shapes","shape","Names and properties"],data2:["Charts and data","data","Read and compare simple charts"],tables3:["Explore the ×3 table","number","A gentle stretch topic"],
 place10000:["Place value to 10,000","number","Thousands and estimation"],operations500:["Four operations","number","Flexible calculation strategies"],tablesCore:["Core times tables","number","×2, ×3, ×4, ×5, ×6, ×8 and ×10"],divisionCore:["Division facts","number","Use multiplication inverses"],fractionsQty:["Fractions of quantities","number","Unit and non-unit fractions"],decimalsTenths:["Tenths and decimals","number","Connect fractions and decimals"],equations:["Patterns and equations","algebra","Unknown values and rules"],measure3:["Time, area and perimeter","measures","Solve practical measure problems"],geometry3:["Angles and transformations","shape","Turns, symmetry and shape"],dataChance3:["Data and chance","data","Graphs and likely outcomes"],
 place100000:["Large place value","number","Read, compare and round numbers"],operations1000:["Operation strategies","number","Multi-step addition and subtraction"],tables12:["Tables to ×12","number","Full multiplication recall"],division12:["Division to 12 × 12","number","Related multiplication facts"],fractionsEquivalent:["Equivalent fractions","number","Compare and rename fractions"],decimalsHundredths:["Decimals to hundredths","number","Place value and calculation"],areaPerim:["Area and perimeter","measures","Measure rectangles and compounds"],geometry4:["Angles and symmetry","shape","Classify and transform shapes"],dataChance4:["Graphs and chance","data","Interpret data and probability language"],
 operationsLarge:["Large-number operations","number","Efficient written and mental methods"],factors:["Factors and multiples","number","Divisibility and prime thinking"],fractionsOps:["Fractions and decimals","number","Compare, convert and calculate"],decimalsPercent:["Decimals and percentages","number","Equivalent representations"],integers:["Positive and negative numbers","number","Number lines and temperature"],algebra5:["Algebraic thinking","algebra","Rules, symbols and unknowns"],measureVolume:["Area, volume and measure","measures","Practical compound measures"],geometry5:["Coordinates and geometry","shape","Angles, coordinates and properties"],statistics:["Statistics","data","Mean, range and displays"],probability:["Probability","data","Compare and express likelihood"],
 operationsReason:["Operations and reasoning","number","Multi-step problem solving"],factorsPrimes:["Factors, multiples and primes","number","Structure of whole numbers"],fractionsAdvanced:["Fraction operations","number","Fractions, decimals and percentages"],percentages:["Percentage applications","number","Discounts and percentage change"],ratio:["Ratio and proportion","number","Scale quantities together"],integers6:["Integer operations","number","Calculate across zero"],algebra6:["Expressions and equations","algebra","Represent and solve relationships"],finance:["Financial maths","measures","Budgets, value and transactions"],geometry6:["Geometry and transformation","shape","Angles, coordinates and scale"],statistics6:["Data investigation","data","Mean, range and inference"],probability6:["Probability models","data","Fractions, decimals and chance"]
};
const CLASSES={
 1:{label:"1st Class",stage:"Stage 2",age:7,tables:[2,5,10],practice:["place100","add20","sub20","patterns","measureEarly","shapeEarly","dataEarly"],explore:["groups","fractionsBasic"]},
 2:{label:"2nd Class",stage:"Stage 2",age:8,tables:[2,5,10],practice:["place1000","add100","sub100","tables2510","divisionBasic","fractionsQuarter","patterns","measure2","shape2","data2"],explore:["tables3"]},
 3:{label:"3rd Class",stage:"Stage 3",age:9,tables:[2,3,4,5,6,8,10],practice:["place10000","operations500","tablesCore","divisionCore","fractionsQty","decimalsTenths","equations","measure3","geometry3"],explore:["dataChance3"]},
 4:{label:"4th Class",stage:"Stage 3",age:10,tables:[2,3,4,5,6,7,8,9,10,11,12],practice:["place100000","operations1000","tables12","division12","fractionsEquivalent","decimalsHundredths","equations","areaPerim","geometry4"],explore:["dataChance4"]},
 5:{label:"5th Class",stage:"Stage 4",age:11,tables:[2,3,4,5,6,7,8,9,10,11,12],practice:["operationsLarge","factors","fractionsOps","decimalsPercent","algebra5","measureVolume","geometry5","statistics"],explore:["integers","probability"]},
 6:{label:"6th Class",stage:"Stage 4",age:12,tables:[2,3,4,5,6,7,8,9,10,11,12],practice:["operationsReason","factorsPrimes","fractionsAdvanced","percentages","ratio","algebra6","finance","geometry6","statistics6"],explore:["integers6","probability6"]}
};
const AVATARS=[{face:"#ffd2b5",hair:"#6a3b24",tag:"⭐"},{face:"#8f5a3c",hair:"#21160f",tag:"🚀"},{face:"#f1b784",hair:"#d06e24",tag:"🎨"},{face:"#6d422e",hair:"#17110f",tag:"⚽"},{face:"#f7c9a8",hair:"#432a75",tag:"🎵"},{face:"#c7875d",hair:"#362014",tag:"🌈"},{face:"#ffd6bd",hair:"#b98b3e",tag:"🧩"},{face:"#9a6549",hair:"#1c1714",tag:"🔭"}];
let data=load(),activeId=data.activeId||null,draft=null,onboardStep=1,playMode="learn",session=null,hintLevel=0,selectedTables=new Set(),beatMode="discover",beatTimer=null,audio=null,gateAnswer=0,holdTimer=null,holdTick=null;
function fresh(){return{version:1,activeId:null,learners:[],settings:{timedFlow:true,celebrations:true,sound:true,sessionLength:8}}}function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(STORE)||"{}"))}catch(_){return fresh()}}function save(){data.activeId=activeId;localStorage.setItem(STORE,JSON.stringify(data))}function learner(){return data.learners.find(x=>x.id===activeId)}function show(id){$$('.screen').forEach(x=>x.hidden=true);$(id).hidden=false;scrollTo(0,0)}function planFor(level){const c=CLASSES[level],p={};c.practice.forEach(id=>p[id]="practice");c.explore.forEach(id=>p[id]="explore");return p}function avatarHTML(id,small=false){const a=AVATARS[id]||AVATARS[0];return`<div class="avatar-face${small?" avatar-sm":""}" style="--face:${a.face};--hair:${a.hair}"><i></i><b>${a.tag}</b></div>`}function stageFor(level){return CLASSES[level].stage}
function ensureLearner(l){l.plan=l.plan||planFor(l.classLevel);l.mastery=l.mastery||{};l.sessions=l.sessions||0;l.totalCorrect=l.totalCorrect||0;l.totalAttempts=l.totalAttempts||0;l.helped=l.helped||0;l.beat=l.beat||{attempts:0,correct:0,tokens:0,best:0};return l}
function profiles(){const root=$("#profiles");root.innerHTML="";data.learners.filter(x=>!x.archived).forEach(l=>{ensureLearner(l);const b=document.createElement("button");b.className="profile";b.innerHTML=`${avatarHTML(l.avatarId)}<strong>${escapeHTML(l.name)}</strong><span>${CLASSES[l.classLevel].label} • Age ${l.age}</span><span class="small">${l.sessions?l.sessions+" quest"+(l.sessions===1?"":"s"):`${stageFor(l.classLevel)} curriculum`}</span>`;b.onclick=()=>chooseLearner(l.id);root.appendChild(b)});const add=document.createElement("button");add.className="profile add";add.innerHTML='<span class="plus">+</span><strong>Add a learner</strong><span>1st–6th Class</span>';add.onclick=()=>startOnboarding();root.appendChild(add)}
function chooseLearner(id){activeId=id;save();home();show("#homeScreen")}function home(){const l=ensureLearner(learner()),c=CLASSES[l.classLevel],counts=countPlan(l.plan);$("#homeAvatar").innerHTML=avatarHTML(l.avatarId,true);$("#welcomeTitle").textContent=`Ready, ${l.name}?`;$("#classLine").textContent=`${c.label} • ${c.stage} Irish curriculum`;$("#learningSummary").textContent=`${counts.practice} to practise • ${counts.explore} to explore`;$("#sessionLine").textContent=`${data.settings.sessionLength} questions • tips always available`;syncSound()}
function startOnboarding(existing=null,step=1){draft=existing?JSON.parse(JSON.stringify(existing)):{id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),name:"",classLevel:1,age:7,avatarId:0,plan:planFor(1),mastery:{},sessions:0,totalCorrect:0,totalAttempts:0,helped:0,beat:{attempts:0,correct:0,tokens:0,best:0}};onboardStep=step;$("#learnerName").value=draft.name;$("#learnerClass").value=draft.classLevel;$("#learnerAge").value=draft.age;renderAvatars();renderOnboard();show("#onboardingScreen")}
function renderOnboard(){onboardStep=Math.max(1,Math.min(3,onboardStep));$("#detailsStep").hidden=onboardStep!==1;$("#planStep").hidden=onboardStep!==2;$("#reviewStep").hidden=onboardStep!==3;$("#stepLabel").textContent=`Step ${onboardStep} of 3`;$$('.stepper i').forEach((x,i)=>x.classList.toggle("on",i<onboardStep));if(onboardStep===2)renderPlanner();if(onboardStep===3)renderReview()}
function renderAvatars(){const root=$("#avatarGrid");root.innerHTML="";AVATARS.forEach((_,i)=>{const b=document.createElement("button");b.className=`avatar-choice${i===draft.avatarId?" selected":""}`;b.setAttribute("aria-label",`Choose avatar ${i+1}`);b.innerHTML=avatarHTML(i);b.onclick=()=>{draft.avatarId=i;renderAvatars()};root.appendChild(b)})}
function classTopics(level){const c=CLASSES[level];return[...c.practice,...c.explore]}function countPlan(plan){return Object.values(plan).reduce((o,v)=>(o[v]=(o[v]||0)+1,o),{practice:0,explore:0,later:0})}
function renderPlanner(){const root=$("#topicPlanner");root.innerHTML="";Object.entries(STRANDS).forEach(([strand,[icon,label]])=>{const ids=classTopics(draft.classLevel).filter(id=>TOPICS[id][1]===strand);if(!ids.length)return;const group=document.createElement("div");group.className="strand-group";group.innerHTML=`<h3>${icon} ${label}</h3><div class="topic-list"></div>`;ids.forEach(id=>{const [name,,desc]=TOPICS[id],state=draft.plan[id]||"later",card=document.createElement("div");card.className="topic-card";card.innerHTML=`<div><strong>${name}</strong><small>${desc}</small></div><button class="topic-state ${state}" data-id="${id}">${state[0].toUpperCase()+state.slice(1)}</button>`;group.querySelector(".topic-list").appendChild(card)});root.appendChild(group)});$$(".topic-state").forEach(b=>b.onclick=()=>cycleTopic(b.dataset.id));const counts=countPlan(draft.plan);$("#planCounts").innerHTML=`<span class="chip practice">${counts.practice||0} Practise</span><span class="chip explore">${counts.explore||0} Explore</span><span class="chip">${counts.later||0} Later</span>`}
function cycleTopic(id){const now=draft.plan[id]||"later",explore=countPlan(draft.plan).explore||0;if(now==="practice")draft.plan[id]=explore<2?"explore":"later";else if(now==="explore")draft.plan[id]="later";else draft.plan[id]="practice";renderPlanner()}
function renderReview(){const counts=countPlan(draft.plan);$("#reviewTitle").textContent=`${draft.name}’s quest is ready`;$("#reviewProfile").innerHTML=`<div class="learner-manage">${avatarHTML(draft.avatarId,true)}<div><strong>${escapeHTML(draft.name)}</strong><span>${CLASSES[draft.classLevel].label} • Age ${draft.age}</span></div></div>`;$("#reviewPlan").innerHTML=`<span class="chip practice">${counts.practice||0} topics to practise</span><span class="chip explore">${counts.explore||0} new topic${counts.explore===1?"":"s"} to explore</span>`}
function storeDraft(){const idx=data.learners.findIndex(x=>x.id===draft.id);if(idx>=0)data.learners[idx]=draft;else data.learners.push(draft);activeId=draft.id;save();home();show("#homeScreen")}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function q(topic,text,answer,key,hints,visual=null,options=null){return{topic,text,answer,key:`${topic}:${key}`,hints,visual,options,started:Date.now(),helped:false}}
function makeQuestion(topic){
 const learn=playMode==="learn",l=learner();
 if(/^place/.test(topic)){const max={place100:99,place1000:999,place10000:9999,place100000:99999}[topic],place=rand(max<100?[10,1]:max<1000?[100,10,1]:max<10000?[1000,100,10]:[10000,1000,100]),digit=rint(2,9),number=digit*place+rint(1,Math.max(2,place-1));return q(topic,`What is the value of ${digit} in ${number}?`,digit*place,`${number}:${digit}`,[`Find the ${place===1?"ones":place===10?"tens":place===100?"hundreds":place===1000?"thousands":"ten-thousands"} place.`,`Write the number in expanded form.`,`For example, the 4 in 4,328 is worth 4,000.`])}
 if(["add20","add100"].includes(topic)){const max=topic==="add20"?20:100,a=rint(2,max-3),b=rint(1,max-a);return q(topic,`${a} + ${b} = ?`,a+b,`${a}+${b}`,[`Start at ${a} and count on ${b}.`,`Split ${b} into tens and ones, then add each part.`,`Example: 24 + 13 = 24 + 10 + 3.`])}
 if(["sub20","sub100"].includes(topic)){const max=topic==="sub20"?20:100,a=rint(6,max),b=rint(1,a-1);return q(topic,`${a} − ${b} = ?`,a-b,`${a}-${b}`,[`Start at ${a} and count back ${b}.`,`Split ${b} into friendly parts.`,`Example: 43 − 12 = 43 − 10 − 2.`])}
 if(["operations500","operations1000","operationsLarge","operationsReason"].includes(topic)){const max={operations500:500,operations1000:1000,operationsLarge:10000,operationsReason:5000}[topic],multiply=topic==="operationsReason"&&Math.random()<.4;if(multiply){const a=rint(3,18),b=rint(3,12),c=rint(2,20);return q(topic,`${a} × ${b} + ${c} = ?`,a*b+c,`${a}x${b}+${c}`,[`Do the multiplication before the addition.`,`Work out ${a} × ${b}, then add ${c}.`,`Example: 6 × 4 + 3 = 24 + 3.`])}const add=Math.random()<.5,a=rint(max/5,max),b=rint(20,Math.min(a-1,max/3));return q(topic,`${a} ${add?"+":"−"} ${b} = ?`,add?a+b:a-b,`${a}${add?"+":"-"}${b}`,[`Estimate first so you know the size of the answer.`,`Partition ${b} by place value.`,`Check using the inverse operation.`])}
 if(["groups","tables2510","tables3","tablesCore","tables12"].includes(topic)){const tables=topic==="groups"?[2,5]:topic==="tables2510"?[2,5,10]:topic==="tables3"?[3]:topic==="tablesCore"?[2,3,4,5,6,8,10]:[2,3,4,5,6,7,8,9,10,11,12],a=rand(tables),b=rint(1,topic==="groups"?6:12);return q(topic,`${a} × ${b} = ?`,a*b,`${a}x${b}`,[`Think of ${a} equal groups of ${b}.`,`Use a nearby fact you already know, then adjust.`,`Example: 6 × 7 can be 5 × 7, then add another 7.`],{kind:"dots",rows:a,cols:b})}
 if(["divisionBasic","divisionCore","division12"].includes(topic)){const top=topic==="divisionBasic"?10:12,a=rint(2,top),b=rint(2,top);return q(topic,`${a*b} ÷ ${a} = ?`,b,`${a*b}/${a}`,[`Ask: ${a} multiplied by what makes ${a*b}?`,`Share ${a*b} into ${a} equal groups.`,`Use the fact ${a} × ${b} = ${a*b}.`],{kind:"dots",rows:a,cols:b})}
 if(["fractionsBasic","fractionsQuarter","fractionsQty","fractionsEquivalent","fractionsOps","fractionsAdvanced"].includes(topic)){if(topic==="fractionsBasic"||topic==="fractionsQuarter"){const d=rand(topic==="fractionsBasic"?[2]:[2,4]),n=rint(1,d-1),ans=`${n}/${d}`;return q(topic,"What fraction of the bar is coloured?",ans,ans,[`Count all the equal parts.`,`Count the coloured parts for the top number.`,`The bottom number tells how many equal parts make the whole.`],{kind:"fraction",parts:d,filled:n},shuffle([ans,`1/${d}`,`${d-n}/${d}`,`${n}/${d+1}`]))}const d=rand([2,3,4,5,8,10]),n=rint(1,d-1),whole=d*rint(2,12);return q(topic,`${n}/${d} of ${whole} = ?`,whole/d*n,`${n}/${d}:${whole}`,[`First find 1/${d} of ${whole}.`,`Divide ${whole} by ${d}, then multiply by ${n}.`,`Example: 3/4 of 20: 20 ÷ 4 = 5, then 5 × 3.`])}
 if(["decimalsTenths","decimalsHundredths","fractionsOps"].includes(topic)){const places=topic==="decimalsTenths"?10:100,a=rint(1,places-2)/places,b=rint(1,places-1)/places,ans=Number((a+b).toFixed(2));return q(topic,`${a} + ${b} = ?`,ans,`${a}+${b}`,[`Line up the decimal points.`,`Add digits with the same place value.`,`Example: 0.4 + 0.3 means 4 tenths + 3 tenths.`])}
 if(["decimalsPercent","percentages"].includes(topic)){const pct=rand([10,20,25,50,75]),base=rand([40,60,80,100,120,160,200]);return q(topic,`${pct}% of ${base} = ?`,base*pct/100,`${pct}:${base}`,[`Start with an easy percentage such as 10%, 25% or 50%.`,`10% means divide by 10; 50% means halve.`,`Example: 25% of 80 is one quarter of 80.`])}
 if(["patterns","equations","algebra5","algebra6"].includes(topic)){if(topic==="patterns"){const step=rand([2,3,5,10]),start=rint(0,15);return q(topic,`${start}, ${start+step}, ${start+2*step}, ?`,start+3*step,`${start}:${step}`,[`Find what changes each time.`,`Subtract neighbouring terms to find the step.`,`Keep adding the same step once more.`])}const x=rint(2,12),a=topic==="equations"?1:rint(2,5),b=rint(2,14),total=a*x+b;return q(topic,a===1?`${b} + □ = ${total}`:`${a}x + ${b} = ${total}. x = ?`,x,`${a}:${b}:${total}`,[`Undo the addition first.`,`Subtract ${b} from ${total}${a>1?`, then divide by ${a}`:""}.`,`Check by putting your answer back into the equation.`])}
 if(["measureEarly","measure2","measure3","areaPerim","measureVolume"].includes(topic)){if(["areaPerim","measure3"].includes(topic)){const w=rint(3,12),h=rint(2,9),area=Math.random()<.5;return q(topic,`Rectangle ${w} cm by ${h} cm: ${area?"area":"perimeter"} = ?`,area?w*h:2*(w+h),`${w}:${h}:${area}`,[area?`Area covers the inside of the shape.`:`Perimeter is the distance around the edge.`,area?`Multiply ${w} by ${h}.`:`Add all four sides.`,area?`Example: 5 cm × 3 cm = 15 cm².`:`Example: 5 + 3 + 5 + 3 = 16 cm.`])}if(topic==="measureVolume"){const a=rint(2,7),b=rint(2,6),c=rint(2,5);return q(topic,`${a} × ${b} × ${c} cuboid: volume = ? cm³`,a*b*c,`${a}:${b}:${c}`,[`Volume counts cubic units inside.`,`Multiply length × width × height.`,`Work with two dimensions first, then multiply by the third.`])}const hour=rint(1,11),minutes=topic==="measureEarly"?30:rand([15,30,45]);return q(topic,`${minutes} minutes after ${hour}:00 is…`,`${hour}:${String(minutes).padStart(2,"0")}`,`${hour}:${minutes}`,[`Move forward ${minutes} minutes from ${hour}:00.`,`A quarter hour is 15 minutes; a half hour is 30.`,`Use a clock face and count in fives.`],null,[`${hour}:${String(minutes).padStart(2,"0")}`,`${hour+1}:00`,`${hour}:${String(60-minutes).padStart(2,"0")}`,`${hour+1}:${String(minutes).padStart(2,"0")}`])}
 if(topic==="finance"){const price=rint(12,60),paid=Math.ceil(price/10)*10;return q(topic,`An item costs €${price}. Change from €${paid} = ?`,paid-price,`${price}:${paid}`,[`Change is the amount paid minus the price.`,`Count up from €${price} to €${paid}.`,`Check by adding the change back to the price.`])}
 if(["shapeEarly","shape2","geometry3","geometry4","geometry5","geometry6"].includes(topic)){if(topic==="shapeEarly"||topic==="shape2"){const s=rand([["triangle",3],["pentagon",5],["hexagon",6],["octagon",8]]);return q(topic,`How many sides has a ${s[0]}?`,s[1],s[0],[`Picture the shape.`,`Trace each straight edge once.`,`The name often gives a clue to the number of sides.`])}const a=rint(30,80),b=rint(30,Math.min(100,140-a));return q(topic,`A triangle has angles ${a}° and ${b}°. Third angle = ?`,180-a-b,`${a}:${b}`,[`Angles in a triangle total 180°.`,`Add the two known angles, then subtract from 180.`,`Check that all three angles add to 180°.`])}
 if(["dataEarly","data2","dataChance3","dataChance4","statistics","statistics6"].includes(topic)){const vals=[rint(3,12),rint(3,12),rint(3,12),rint(3,12)],range=topic==="statistics"||topic==="statistics6";return q(topic,range?`Find the range: ${vals.join(", ")}`:`Largest value in ${vals.join(", ")} = ?`,range?Math.max(...vals)-Math.min(...vals):Math.max(...vals),vals.join("-"),[range?`Range means highest minus lowest.`:`Compare the values one place at a time.`,range?`Circle the highest and lowest values first.`:`Eliminate values that are clearly smaller.`,range?`Subtract the smallest from the largest.`:`Check every value before deciding.`])}
 if(["probability","probability6"].includes(topic)){const red=rint(2,5),blue=rint(1,5),total=red+blue,ans=`${red}/${total}`;return q(topic,`${red} red and ${blue} blue counters. P(red) = ?`,ans,`${red}:${blue}`,[`Probability is favourable outcomes over all outcomes.`,`There are ${total} counters altogether.`,`Put ${red} over ${total}.`],null,shuffle([ans,`${blue}/${total}`,`${red}/${blue}`,`1/${total}`]))}
 if(["integers","integers6"].includes(topic)){const a=rint(-12,12),b=rint(-10,14),ans=a+b;return q(topic,`${a} + ${b<0?`(${b})`:b} = ?`,ans,`${a}:${b}`,[`Picture a number line.`,`Adding a positive moves right; adding a negative moves left.`,`Start at ${a} and move ${Math.abs(b)} places ${b<0?"left":"right"}.`])}
 if(["factors","factorsPrimes"].includes(topic)){const base=rand([12,18,20,24,30,36]),f=[];for(let i=2;i<base;i++)if(base%i===0)f.push(i);const ans=rand(f),wrong=[7,11,13,base-1].filter(n=>base%n!==0).slice(0,3);return q(topic,`Which is a factor of ${base}?`,ans,`${base}:${ans}`,[`A factor divides exactly with no remainder.`,`Try dividing ${base} by each option.`,`A factor pairs with another whole number to make ${base}.`],null,shuffle([ans,...wrong]))}
 if(topic==="ratio"){const a=rint(2,5),b=rint(2,6),scale=rint(2,5);return q(topic,`Red : blue = ${a} : ${b}. If red = ${a*scale}, blue = ?`,b*scale,`${a}:${b}:${scale}`,[`Both parts of a ratio scale by the same amount.`,`Red was multiplied by ${scale}.`,`Multiply the blue part, ${b}, by ${scale} too.`])}
 return q(topic,"2 + 2 = ?",4,"fallback",["Count on two more.","Use two groups of two.","2 + 2 makes 4."]);
}
function selectedTopic(){const l=learner(),pool=[];Object.entries(l.plan).forEach(([id,state])=>{if(state==="later"||playMode==="challenge"&&state==="explore")return;const m=l.mastery[id],weight=state==="explore"?1:!m?4:Math.max(1,Math.ceil(5-(m.correct/m.attempts)*3));for(let i=0;i<weight;i++)pool.push(id)});return rand(pool.length?pool:CLASSES[l.classLevel].practice)}
function startQuest(opts={}){clearInterval(beatTimer);const total=opts.beatMode==="flow"?Infinity:opts.beatMode?opts.beatMode==="discover"?10:12:data.settings.sessionLength;session={index:0,total,correct:0,independent:0,score:0,locked:false,beatMode:opts.beatMode||null,timeLeft:60};show("#gameScreen");nextQuestion();if(opts.beatMode==="flow")beatTimer=setInterval(()=>{if(!session)return;session.timeLeft--;$("#topicContext").textContent=`Personal best • ${session.timeLeft}s left`;if(session.timeLeft<=0)finishQuest()},1000)}
function beatQuestion(){const l=learner(),table=rand([...selectedTables]),max=l.classLevel<=2?10:12,b=rint(1,max),divide=beatMode!=="discover"&&Math.random()<.35;return q("beat",divide?`${table*b} ÷ ${table} = ?`:`${table} × ${b} = ?`,divide?b:table*b,`${table}:${b}:${divide}`,[`Use the related multiplication fact.`,`Picture ${table} equal groups of ${b}.`,`${table} × ${b} = ${table*b}.`],{kind:"dots",rows:table,cols:b})}
function nextQuestion(){if(!session||session.index>=session.total){finishQuest();return}session.locked=false;hintLevel=0;const topic=session.beatMode?"beat":selectedTopic(),question=session.beatMode?beatQuestion():makeQuestion(topic);session.q=question;const l=learner();$("#gameAvatar").innerHTML=avatarHTML(l.avatarId,true);$("#topicTitle").textContent=topic==="beat"?"Beat Quest":TOPICS[topic][0];$("#topicContext").textContent=session.beatMode?session.beatMode==="flow"?`Personal best • ${session.timeLeft}s left`:`${session.beatMode[0].toUpperCase()+session.beatMode.slice(1)} • accuracy builds the beat`:(l.plan[topic]==="explore"?"New topic to explore • extra help available":playMode==="challenge"?"One try • tips still available":"Build understanding, then fluency");$("#questionText").textContent=question.text;$("#feedback").textContent="";$("#feedback").className="feedback";renderVisual(question.visual);renderAnswers();updateHUD()}
function renderVisual(v){const root=$("#questionVisual");root.innerHTML="";if(!v)return;if(v.kind==="dots"&&v.rows*v.cols<=72){const d=document.createElement("div");d.className="dots";d.style.gridTemplateColumns=`repeat(${v.cols},14px)`;for(let i=0;i<v.rows*v.cols;i++)d.innerHTML+='<i class="dot"></i>';root.appendChild(d)}if(v.kind==="fraction"){const b=document.createElement("div");b.className="fractionbar";b.style.gridTemplateColumns=`repeat(${v.parts},1fr)`;for(let i=0;i<v.parts;i++)b.innerHTML+=`<i class="${i<v.filled?"on":""}"></i>`;root.appendChild(b)}}
function options(qn){if(qn.options)return [...new Set(qn.options)].slice(0,4);if(typeof qn.answer!=="number")return[qn.answer,"0","1","None"];const set=new Set([qn.answer]),scale=Math.max(1,Math.round(Math.abs(qn.answer)*.12));for(const d of shuffle([-10,-5,-scale,-2,-1,1,2,scale,5,10])){if(set.size===4)break;const v=Number((qn.answer+d).toFixed(2));if(qn.topic==="integers"||qn.topic==="integers6"||v>=0)set.add(v)}return shuffle([...set])}
function renderAnswers(){const root=$("#answers");root.innerHTML='<div class="answers"></div>';options(session.q).forEach(value=>{const b=document.createElement("button");b.className="answer";b.textContent=value;b.onclick=()=>answer(value,b);root.firstChild.appendChild(b)})}
function answer(value,button){if(session.locked)return;session.locked=true;const qn=session.q,ok=String(value)===String(qn.answer),l=learner(),elapsed=Date.now()-qn.started;let m=l.mastery[qn.topic]||{attempts:0,correct:0,helped:0,totalMs:0};m.attempts++;m.correct+=ok?1:0;m.helped+=qn.helped?1:0;m.totalMs+=elapsed;l.mastery[qn.topic]=m;l.totalAttempts++;if(ok){l.totalCorrect++;session.correct++;session.score++;if(!qn.helped)session.independent++;button.classList.add("correct");$("#feedback").textContent=qn.helped?"That’s it—your strategy worked!":`Yes, ${l.name}!`;$("#feedback").className="feedback good";sound("correct")}else{button.classList.add("wrong");$("#feedback").textContent=`The answer is ${qn.answer}. This idea will come back later.`;$("#feedback").className="feedback bad";sound("wrong")}if(session.beatMode){l.beat.attempts++;l.beat.correct+=ok?1:0;if(ok)l.beat.tokens+=session.beatMode==="build"?3:session.beatMode==="discover"?2:1}session.index++;save();updateHUD();setTimeout(nextQuestion,ok?650:1150)}
function updateHUD(){if(!session)return;$("#score").textContent=session.score;$("#progressBar").style.width=session.total===Infinity?"100%":`${session.index/session.total*100}%`}
function finishQuest(){if(!session)return;clearInterval(beatTimer);const l=learner(),s=session;l.sessions++;if(s.beatMode==="flow")l.beat.best=Math.max(l.beat.best,s.correct);save();session=null;show("#resultsScreen");const pct=s.index?Math.round(s.correct/s.index*100):0;$("#resultsTitle").textContent=pct>=80?`Brilliant work, ${l.name}!`:`Good learning, ${l.name}!`;$("#resultsMessage").textContent=s.beatMode?"Your own accuracy and recall are building the rhythm.":"Your next quest will revisit developing ideas and keep secure topics fresh.";$("#accuracyResult").textContent=pct+"%";$("#independentResult").textContent=s.independent;$("#scoreResult").textContent=s.score;sound("finish")}
function openHelp(){if(!session)return;session.q.helped=true;learner().helped++;hintLevel=0;renderHints();$("#helpDialog").showModal()}function renderHints(){const root=$("#hintContent");root.innerHTML="";session.q.hints.slice(0,hintLevel+1).forEach((h,i)=>{const d=document.createElement("div");d.className="hint-step";d.innerHTML=`<strong>${i===0?"Tip":i===1?"Show me":"Similar example"}</strong><span>${escapeHTML(h)}</span>`;root.appendChild(d)});$("#moreHelp").hidden=hintLevel>=2}function moreHelp(){hintLevel=Math.min(2,hintLevel+1);renderHints()}
function openBeat(){const l=learner(),c=CLASSES[l.classLevel];selectedTables=new Set([c.tables[0]]);beatMode="discover";$("#beatCopy").textContent=`Made for ${l.name}: private practice using ${c.label} table choices.`;renderBeat();show("#beatScreen")}function renderBeat(){const c=CLASSES[learner().classLevel],root=$("#tableChoices");root.innerHTML="";c.tables.forEach(n=>{const b=document.createElement("button");b.className=`chip ${selectedTables.has(n)?"practice":""}`;b.textContent=`×${n}`;b.onclick=()=>{if(selectedTables.has(n)&&selectedTables.size>1)selectedTables.delete(n);else selectedTables.add(n);renderBeat()};root.appendChild(b)});$$('[data-beat]').forEach(b=>{const locked=b.dataset.beat==="flow"&&!data.settings.timedFlow;b.classList.toggle("selected",b.dataset.beat===beatMode);b.style.opacity=locked?".5":"1"});$("#startBeat").textContent=`Start ${beatMode[0].toUpperCase()+beatMode.slice(1)}`;$("#beatStatus").textContent=beatMode==="flow"?(data.settings.timedFlow?"60 seconds • personal best":"A grown-up has turned off timed play"):beatMode==="discover"?"10 questions • untimed":"12 adaptive questions • untimed"}
function openGate(){gateAnswer=0;$("#holdGate").hidden=false;$("#mathGate").hidden=true;$("#holdButton").style.setProperty("--hold","0%");$("#gateDialog").showModal()}function startHold(){let p=0;clearInterval(holdTick);holdTick=setInterval(()=>{p+=5;$("#holdButton").style.setProperty("--hold",`${p}%`)},75);holdTimer=setTimeout(()=>{cancelHold();const a=rint(3,9),b=rint(2,8);gateAnswer=a*b;$("#gateQuestion").textContent=`${a} × ${b} = ?`;$("#gateAnswer").value="";$("#holdGate").hidden=true;$("#mathGate").hidden=false;setTimeout(()=>$("#gateAnswer").focus(),50)},1500)}function cancelHold(){clearTimeout(holdTimer);clearInterval(holdTick)}function unlock(){if(Number($("#gateAnswer").value)!==gateAnswer){$("#gateError").textContent="Not quite—try once more.";return}$("#gateDialog").close();renderParent();show("#grownupsScreen")}
function renderParent(){const l=learner(),root=$("#parentLearners");root.innerHTML="<h2>Learners</h2>";data.learners.forEach(x=>{const d=document.createElement("div"),hideControl=x.id===activeId?'<span class="small">Current learner</span>':`<button class="linkbtn archive-person" data-id="${x.id}">${x.archived?"Restore":"Hide"}</button>`;d.className="learner-manage";d.innerHTML=`${avatarHTML(x.avatarId,true)}<div><strong>${escapeHTML(x.name)}</strong><span>${CLASSES[x.classLevel].label}${x.archived?" • hidden":""}</span></div><div><button class="secondary edit-person" data-id="${x.id}">Edit</button> ${hideControl}</div>`;root.appendChild(d)});$$(".edit-person").forEach(b=>b.onclick=()=>startOnboarding(data.learners.find(x=>x.id===b.dataset.id)));$$(".archive-person").forEach(b=>b.onclick=()=>{const x=data.learners.find(y=>y.id===b.dataset.id);x.archived=!x.archived;save();renderParent()});const accuracy=l.totalAttempts?Math.round(l.totalCorrect/l.totalAttempts*100):0;$("#parentStats").innerHTML=`<div class="stat"><b>${l.sessions}</b><span>quests</span></div><div class="stat"><b>${accuracy||"—"}${accuracy?"%":""}</b><span>accuracy</span></div><div class="stat"><b>${l.helped}</b><span>tips opened</span></div>`;const list=$("#masteryList");list.innerHTML="";Object.entries(l.plan).filter(([,s])=>s!=="later").forEach(([id,state])=>{const m=l.mastery[id],pct=m?Math.round(m.correct/m.attempts*100):0;list.innerHTML+=`<div class="mastery"><strong>${TOPICS[id][0]}</strong><span>${state} • ${m?m.attempts+" attempts":"not started"}</span><i><b style="width:${pct}%"></b></i></div>`});syncSettings()}
function syncSettings(){$("#timedSetting").classList.toggle("on",data.settings.timedFlow);$("#celebrationSetting").classList.toggle("on",data.settings.celebrations);$("#soundSetting").classList.toggle("on",data.settings.sound);$("#sessionSetting").value=data.settings.sessionLength;syncSound()}
function exportData(){const blob=new Blob([JSON.stringify({app:"Maths Quest",version:1,exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`maths-quest-progress-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}async function importData(file){try{const payload=JSON.parse(await file.text());if(payload.app!=="Maths Quest"||!payload.data?.learners)throw Error();data=Object.assign(fresh(),payload.data);activeId=data.activeId||data.learners[0]?.id;save();renderParent()}catch(_){alert("That is not a valid Maths Quest progress file.")}}
function audioCtx(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audio)audio=new C();if(audio.state==="suspended")audio.resume();return audio}function tone(f,d=.1,delay=0){if(!data.settings.sound)return;const c=audioCtx();if(!c)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.frequency.value=f;o.type="triangle";g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.035,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(c.destination);o.start(t);o.stop(t+d+.03)}function sound(k){if(k==="correct"){tone(523,.12);tone(659,.14,.08)}else if(k==="wrong")tone(220,.16);else if(k==="finish")[523,659,784].forEach((f,i)=>tone(f,.18,i*.08));else tone(430,.06)}function syncSound(){$$("[data-sound]").forEach(b=>{b.setAttribute("aria-label",data.settings.sound?"Turn sound off":"Turn sound on");b.querySelector(".sound-icon").textContent=data.settings.sound?"🔊":"🔇";const s=b.querySelector(".sound-label");if(s)s.textContent=data.settings.sound?"Sound":"Muted"})}
function setup(){Object.entries(CLASSES).forEach(([n,c])=>$("#learnerClass").insertAdjacentHTML("beforeend",`<option value="${n}">${c.label}</option>`));for(let a=6;a<=13;a++)$("#learnerAge").insertAdjacentHTML("beforeend",`<option>${a}</option>`);profiles();syncSound();if(!data.learners.length)startOnboarding();else show("#profilesScreen");
 $$("[data-sound]").forEach(b=>b.onclick=()=>{data.settings.sound=!data.settings.sound;save();syncSound();sound("tap")});$("#onboardBack").onclick=()=>onboardStep>1?(onboardStep--,renderOnboard()):(profiles(),show("#profilesScreen"));$("#learnerClass").onchange=e=>{draft.classLevel=Number(e.target.value);draft.age=CLASSES[draft.classLevel].age;draft.plan=planFor(draft.classLevel);$("#learnerAge").value=draft.age};$("#detailsNext").onclick=()=>{draft.name=$("#learnerName").value.trim();draft.classLevel=Number($("#learnerClass").value);draft.age=Number($("#learnerAge").value);if(!draft.name){$("#learnerName").focus();return}onboardStep=2;renderOnboard()};$("#planBack").onclick=()=>{onboardStep=1;renderOnboard()};$("#planNext").onclick=()=>{if(!countPlan(draft.plan).practice){alert("Choose at least one topic to practise.");return}onboardStep=3;renderOnboard()};$("#reviewBack").onclick=()=>{onboardStep=2;renderOnboard()};$("#saveLearner").onclick=storeDraft;
 $("#switchLearner").onclick=()=>{profiles();show("#profilesScreen")};$("#editPlan").onclick=()=>startOnboarding(learner(),2);$("#modeGrid").onclick=e=>{const b=e.target.closest(".mode");if(!b)return;playMode=b.dataset.mode;$$('#modeGrid .mode').forEach(x=>x.classList.toggle("selected",x===b))};$("#startQuest").onclick=()=>startQuest();$("#leaveQuest").onclick=()=>{clearInterval(beatTimer);session=null;home();show("#homeScreen")};$("#playAgain").onclick=()=>startQuest();$("#resultsHome").onclick=()=>{home();show("#homeScreen")};
 $("#helpButton").onclick=openHelp;$("#closeHelp").onclick=()=>$("#helpDialog").close();$("#useTip").onclick=()=>$("#helpDialog").close();$("#moreHelp").onclick=moreHelp;$("#beatButton").onclick=openBeat;$("#beatBack").onclick=()=>{home();show("#homeScreen")};$$('[data-beat]').forEach(b=>b.onclick=()=>{if(b.dataset.beat==="flow"&&!data.settings.timedFlow)return;beatMode=b.dataset.beat;renderBeat()});$("#startBeat").onclick=()=>{if(beatMode==="flow"&&!data.settings.timedFlow)return;startQuest({beatMode})};
 $("#grownupsButton").onclick=openGate;$("#closeGate").onclick=()=>{cancelHold();$("#gateDialog").close()};$("#holdButton").onpointerdown=startHold;$("#holdButton").onpointerup=cancelHold;$("#holdButton").onpointerleave=cancelHold;$("#holdButton").onkeydown=e=>{if((e.key===" "||e.key==="Enter")&&!e.repeat){e.preventDefault();startHold()}};$("#holdButton").onkeyup=e=>{if(e.key===" "||e.key==="Enter")cancelHold()};$("#unlockButton").onclick=unlock;$("#gateAnswer").onkeydown=e=>{if(e.key==="Enter")unlock()};$("#grownupsBack").onclick=()=>{home();show("#homeScreen")};$("#timedSetting").onclick=()=>{data.settings.timedFlow=!data.settings.timedFlow;save();syncSettings()};$("#celebrationSetting").onclick=()=>{data.settings.celebrations=!data.settings.celebrations;save();syncSettings()};$("#soundSetting").onclick=()=>{data.settings.sound=!data.settings.sound;save();syncSettings()};$("#sessionSetting").onchange=e=>{data.settings.sessionLength=Number(e.target.value);save()};$("#exportData").onclick=exportData;$("#importData").onclick=()=>$("#importFile").click();$("#importFile").onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$("#resetLearner").onclick=()=>{if(confirm(`Reset ${learner().name}’s progress? Their profile and learning plan will remain.`)){const l=learner();l.mastery={};l.sessions=0;l.totalCorrect=0;l.totalAttempts=0;l.helped=0;l.beat={attempts:0,correct:0,tokens:0,best:0};save();renderParent()}};
 window.addEventListener("offline",()=>$("#offlineToast").hidden=false);window.addEventListener("online",()=>$("#offlineToast").hidden=true);if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").then(reg=>{const ready=w=>{$("#updateToast").hidden=false;$("#updateButton").onclick=()=>w.postMessage("SKIP_WAITING")};if(reg.waiting)ready(reg.waiting);reg.onupdatefound=()=>{const worker=reg.installing;if(worker)worker.onstatechange=()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)ready(worker)}}}).catch(()=>{}));let refreshing=false;navigator.serviceWorker?.addEventListener("controllerchange",()=>{if(!refreshing){refreshing=true;location.reload()}})
}
setup();
})();
